### PR TITLE
Elastic Beanstalk

### PR DESCRIPTION
**Pull request by PavelZaletski**
1 - Dockerfile is prepared, image is building. Image size is minimised to be less than 500 MB.
2 - Dockerfile is optimized. Files that change more often and commands that depend on them should be included later, files and commands that change less should be at the top.
3 - Folders are added to .dockerignore, with explanations. At least 2 big directories should be excluded from build context. Elastic Beanstalk application is initialized.
4 - Environment is created and the app is deployed to the AWS cloud. You must provide a link to your GitHub repo with Cart API service or PR with created Dockerfile and related configurations.
5 - FE application is updated with Cart API endpoint. You must provide a PR with updates in your FE repository

FrontEnd PR - https://github.com/PavelZaletski/nodejs-aws-fe/pull/6

Screen Shot 2020-12-06 at 5 30 36 PM

Elastic Beanstalk URL - http://pavelzaletski-cart-api-dev.eu-west-1.elasticbeanstalk.com/

ECR:

Screen Shot 2020-12-06 at 5 41 21 PM

### CODE REVIEW

**Comment by izzetbek** [comment]
Please, provide url of yout FE application

**Comment by PavelZaletski** [comment]
> Please, provide url of yout FE application

https://dsb3s2ts35uzs.cloudfront.net/

**Comment by izzetbek** [comment]
Check your cart api proxy
https://j9rgc0g4t0.execute-api.eu-west-1.amazonaws.com/dev/api/api/profile/cart - incorrect path provided for FE app.

**Comment by PavelZaletski** [comment]
> Check your cart api proxy
> https://j9rgc0g4t0.execute-api.eu-west-1.amazonaws.com/dev/api/api/profile/cart - incorrect path provided for FE app.

Fixed. Now it works.

Screen Shot 2020-12-08 at 6 04 06 PM

**Comment by izzetbek** [comment]
👍

**Pull request merged**
